#!/bin/sh

mount -t proc proc proc
mount /dev/pts
rm -f /var/run/*.pid
rm -f /tmp/*
ifconfig lo 127.0.0.1 up
/etc/init.d/syslog start
/etc/init.d/netconf start
# Initialize RNG
/etc/init.d/Srandom
exit 0
